[package]
name = "crowdfunding"
type = "contract"
authors = [""]
compiler_version = ">=0.27.0"

[dependencies]
aztec      = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.34.0", directory="noir-projects/aztec-nr/aztec" }
value_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.34.0", directory="noir-projects/aztec-nr/value-note" }
